# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 312223b3a78e7c67cc649971f0695592ecee92c0a9fdd0a720d5197bff0f289cc20f8abd4d18efe0494ca059ecb300545745e2ca87f556df3df655b466a6f403

test:
  secret_key_base: 99dfa17089a05aa4a68f17f1a28285396be8b41571b45ead7423bbb23b433cc52d00031b52f58b24dd87324871d51742f014c93f00c41f1ceda148ef9f508ce0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
